name: Goldman
favicon: null
layout_spectrum: 0.422297
typography_spectrum: 0.8703
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#D8D0B8'
    - '#284870'
    - '#789078'
    - '#C85858'
    - '#D89890'
  brandStrength: 0.673933605896309
  lightness: 0.5712536531500518
  saturation: 0.5164753457065672
  rhythmicContrast: 0.5102125192061067
purpose: []
